# Generated by Django 3.0 on 2020-07-04 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='weight',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='weight'),
        ),
    ]
